### ISSUE TITLE
agensgraph-nodejs status

### ISSUE THREAD

**Issue by ansarizafar** [bitnine-oss/agensgraph-nodejs#10]
Whats is the status of agensgraph-nodejs. Is it available for production use? Does agensgraph-nodejs support Async/wait?

**Comment by ansarizafar** [comment]
@bylee5 Is this project dead?

**Comment by bylee5** [comment]
This project is alive.
agensgraph-nodejs is under development for community not official.

**Comment by ansarizafar** [comment]
agensgraph-nodejs has not been updated since last December and doesn't support promise/async/await. Is there any plan for an official Nodejs driver with  promise/async/await support?

**Comment by bylee5** [comment]
agensgraph-nodejs based on node-postgres can perform promise/async/await.
For more information, see the node-postgres [documentation](https://node-postgres.com/api/client).
