### ISSUE TITLE
[bug]  field count and object's attribute count mismatch in query result 

### ISSUE THREAD

**Issue by callin2** [bitnine-oss/agensgraph-nodejs#2]
When I execute a query like this   " select 1+1,  3.0/4,  'abcd' as col2  "

I got result like below image.

![image](https://user-images.githubusercontent.com/656944/34031354-425e607a-e1b4-11e7-826a-5ca131be6381.png)

field count is 3  but rows has 2 attributes

**Comment by bylee5** [comment]
Columns with the same name are overridden by the parser.
If you do not want to override, you can use [rowMode](https://node-postgres.com/features/queries) as rowMode: 'array' in the query.
The rowMode can be used as follows.

        var gueryString = {
            text: "select 1+1, 3.0/4, 'abcd' as col2",
            rowMode: 'array'
        };
        client.query(gueryString, function (err, res) {
            if (err) throw err;
            console.log(res);
        });

The following is the result of the above query.

Result {
  command: 'SELECT',
  rowCount: 1,
  oid: NaN,
  rows: [ [ 2, '0.75000000000000000000', 'abcd' ] ],
  fields:
   [ Field {
       name: '?column?',
       tableID: 0,
       columnID: 0,
       dataTypeID: 23,
       dataTypeSize: 4,
       dataTypeModifier: -1,
       format: 'text' },
     Field {
       name: '?column?',
       tableID: 0,
       columnID: 0,
       dataTypeID: 1700,
       dataTypeSize: -1,
       dataTypeModifier: -1,
       format: 'text' },
     Field {
       name: 'col2',
       tableID: 0,
       columnID: 0,
       dataTypeID: 705,
       dataTypeSize: -2,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers:
   [ [Function: parseInteger],
     [Function: noParse],
     [Function: noParse] ],
  RowCtor: null,
  rowAsArray: true,
  parseRow: [Function],
  _getTypeParser: [Function: bound ] }

**Comment by callin2** [comment]
thank you!
