### ISSUE TITLE
post install error "pegjs not found"

### ISSUE THREAD

**Issue by callin2** [bitnine-oss/agensgraph-nodejs#9]
while postinstall process.
if target machine has no pegjs "gloabl" installed then error occur.

It seems to resolve if you change post install script from "pegjs ... "  to "npx pegjs ..."

**Comment by bylee5** [comment]
@callin2 
Is it awkward to install pegjs with global mode?

**Comment by callin2** [comment]
if you use 'npx' then you don't need to install pegjs in global mode.
